local colors = require("drxvim.themes").getCurrentTheme()

return {
  GitSignsCurrentLineBlame = { fg = colors.grey_fg },
  diffAdded = { fg = colors.green },
  diffRemoved = { fg = colors.red },
  diffChanged = { fg = colors.orange },
  diffFile = { fg = colors.color7 },
  diffLine = { fg = colors.color1 },
  diffIndexLine = { fg = colors.color12 },
  diffOldFile = { fg = colors.baby_pink },
  diffNewFile = { fg = colors.blue },
  DiffAdd = { fg = colors.blue },
  DiffAdded = { fg = colors.green },
  DiffChange = { fg = colors.light_grey },
  DiffChangeDelete = { fg = colors.red },
  DiffModified = { fg = colors.orange },
  DiffDelete = { fg = colors.red },
  DiffRemoved = { fg = colors.red },
  DiffText = { fg = colors.white, bg = colors.black2 },

  -- Git commits
  gitcommitOverflow = { fg = colors.base08 },
  gitcommitSummary = { fg = colors.base0B },
  gitcommitComment = { fg = colors.base03 },
  gitcommitUntracked = { fg = colors.base03 },
  gitcommitDiscarded = { fg = colors.base03 },
  gitcommitSelected = { fg = colors.base03 },
  gitcommitHeader = { fg = colors.base0E },
  gitcommitSelectedType = { fg = colors.base0D },
  gitcommitUnmergedType = { fg = colors.base0D },
  gitcommitDiscardedType = { fg = colors.base0D },
  gitcommitBranch = { fg = colors.base09, bold = true },
  gitcommitUntrackedFile = { fg = colors.base0A },
  gitcommitUnmergedFile = { fg = colors.base08, bold = true },
  gitcommitDiscardedFile = { fg = colors.base08, bold = true },
  gitcommitSelectedFile = { fg = colors.base0B, bold = true },

  -- New highlight groups for oil-git-status.nvim
  OilGitStatusIndexUnmodified = { fg = colors.grey },
  OilGitStatusWorkingTreeUnmodified = { fg = colors.grey },
  OilGitStatusIndexIgnored = { fg = colors.base03 },
  OilGitStatusWorkingTreeIgnored = { fg = colors.base03 },
  OilGitStatusIndexUntracked = { fg = colors.base0A },
  OilGitStatusWorkingTreeUntracked = { fg = colors.base0A },
  OilGitStatusIndexAdded = { fg = colors.green },
  OilGitStatusWorkingTreeAdded = { fg = colors.green },
  OilGitStatusIndexCopied = { fg = colors.blue },
  OilGitStatusWorkingTreeCopied = { fg = colors.blue },
  OilGitStatusIndexDeleted = { fg = colors.red },
  OilGitStatusWorkingTreeDeleted = { fg = colors.red },
  OilGitStatusIndexModified = { fg = colors.orange },
  OilGitStatusWorkingTreeModified = { fg = colors.orange },
  OilGitStatusIndexRenamed = { fg = colors.purple },
  OilGitStatusWorkingTreeRenamed = { fg = colors.purple },
  OilGitStatusIndexTypeChanged = { fg = colors.yellow },
  OilGitStatusWorkingTreeTypeChanged = { fg = colors.yellow },
  OilGitStatusIndexUnmerged = { fg = colors.red, bold = true },
  OilGitStatusWorkingTreeUnmerged = { fg = colors.red, bold = true },
}
